tasks:
  - init: |
      rvm install 3.0.3 --default
      gem install rails
      bundle install
      sudo apt install -y postgresql postgresql-contrib libpq-dev
      rails db:migrate
      rails db:seed
    command: |
      rails server
ports:
  - port: 3000
    onOpen: open-browser
vscode:
  extensions:
    - bung87.rails
    - sianglim.slim
    - bung87.vscode-gemfile
    - alexcvzz.vscode-sqlite
    - rebornix.ruby
    - wingrunr21.vscode-ruby
